name: Docker Tutorial
description:  Data and Network Management for Containers

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

#url: http://127.0.0.1:4000
url: http://nkhare.github.io/data_and_network_containers
permalink: /:title/
owner:
    name: Neependra Khare
    website: www.neependra.net
    twitter: neependra
    github: nkhare
    disqus_shortname: #

ga_id: #
ga_username: #

#timezone: Africa/Accra
